# Generated by Django 5.2.6 on 2025-10-30 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profesionales', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estadodeconsulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Estado de Consulta',
                'verbose_name_plural': 'Estados de Consulta',
                'db_table': 'estadodeconsulta',
                'ordering': ['estado'],
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.TimeField(unique=True)),
            ],
            options={
                'verbose_name': 'Horario',
                'verbose_name_plural': 'Horarios',
                'db_table': 'horario',
                'ordering': ['hora'],
            },
        ),
        migrations.CreateModel(
            name='Tipodeconsulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreconsulta', models.CharField(max_length=255, unique=True)),
                ('permite_agendamiento_web', models.BooleanField(default=False, help_text='Pacientes pueden agendar desde la web')),
                ('requiere_aprobacion', models.BooleanField(default=False, help_text='Requiere aprobacion de staff antes de confirmar')),
                ('es_urgencia', models.BooleanField(default=False, help_text='Es consulta urgente (prioridad alta)')),
                ('duracion_estimada', models.IntegerField(default=30, help_text='Duracion estimada en minutos')),
            ],
            options={
                'verbose_name': 'Tipo de Consulta',
                'verbose_name_plural': 'Tipos de Consulta',
                'db_table': 'tipodeconsulta',
                'ordering': ['nombreconsulta'],
            },
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('en_consulta', 'En Consulta'), ('diagnosticada', 'Diagnosticada'), ('con_plan', 'Con Plan'), ('completada', 'Completada'), ('cancelada', 'Cancelada'), ('no_asistio', 'No Asistio')], default='pendiente', max_length=20)),
                ('fecha_preferida', models.DateField(blank=True, null=True)),
                ('horario_preferido', models.CharField(choices=[('manana', 'Manana (8am-12pm)'), ('tarde', 'Tarde (2pm-6pm)'), ('noche', 'Noche (6pm-8pm)'), ('cualquiera', 'Cualquier horario')], default='cualquiera', max_length=20)),
                ('fecha_consulta', models.DateField(blank=True, null=True)),
                ('hora_consulta', models.TimeField(blank=True, null=True)),
                ('hora_llegada', models.DateTimeField(blank=True, null=True)),
                ('hora_inicio_consulta', models.DateTimeField(blank=True, null=True)),
                ('hora_fin_consulta', models.DateTimeField(blank=True, null=True)),
                ('tipo_consulta', models.CharField(blank=True, choices=[('primera_vez', 'Primera Vez'), ('control', 'Control'), ('tratamiento', 'Tratamiento'), ('urgencia', 'Urgencia')], max_length=20, null=True)),
                ('motivo_consulta', models.TextField(blank=True, null=True)),
                ('notas_recepcion', models.TextField(blank=True, null=True)),
                ('motivo_cancelacion', models.TextField(blank=True, null=True)),
                ('duracion_estimada', models.IntegerField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('diagnostico', models.TextField(blank=True, null=True)),
                ('tratamiento', models.TextField(blank=True, null=True)),
                ('costo_consulta', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('requiere_pago', models.BooleanField(default=False)),
                ('cododontologo', models.ForeignKey(blank=True, db_column='cododontologo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='profesionales.odontologo')),
                ('codpaciente', models.ForeignKey(db_column='codpaciente', on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.paciente')),
                ('codrecepcionista', models.ForeignKey(blank=True, db_column='codrecepcionista', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='profesionales.recepcionista')),
                ('idestadoconsulta', models.ForeignKey(db_column='idestadoconsulta', on_delete=django.db.models.deletion.DO_NOTHING, to='citas.estadodeconsulta')),
                ('idhorario', models.ForeignKey(db_column='idhorario', on_delete=django.db.models.deletion.DO_NOTHING, to='citas.horario')),
                ('idtipoconsulta', models.ForeignKey(db_column='idtipoconsulta', on_delete=django.db.models.deletion.DO_NOTHING, to='citas.tipodeconsulta')),
            ],
            options={
                'verbose_name': 'Consulta',
                'verbose_name_plural': 'Consultas',
                'db_table': 'consulta',
                'ordering': ['-fecha'],
            },
        ),
    ]
