# Generated by Django 5.2.6 on 2025-10-30 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Odontologo',
            fields=[
                ('codusuario', models.OneToOneField(db_column='codusuario', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='usuarios.usuario')),
                ('especialidad', models.CharField(blank=True, max_length=255, null=True)),
                ('experienciaprofesional', models.TextField(blank=True, null=True)),
                ('nromatricula', models.CharField(blank=True, max_length=100, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Odontólogo',
                'verbose_name_plural': 'Odontólogos',
                'db_table': 'odontologo',
            },
        ),
        migrations.CreateModel(
            name='Recepcionista',
            fields=[
                ('codusuario', models.OneToOneField(db_column='codusuario', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='usuarios.usuario')),
                ('habilidadessoftware', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Recepcionista',
                'verbose_name_plural': 'Recepcionistas',
                'db_table': 'recepcionista',
            },
        ),
    ]
