# Generated by Django 5.2.6 on 2025-10-30 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Respaldo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('ruta_archivo', models.CharField(max_length=512)),
                ('tipo_respaldo', models.CharField(choices=[('COMPLETO', 'Completo'), ('INCREMENTAL', 'Incremental'), ('MANUAL', 'Manual')], max_length=50)),
                ('tamaño_bytes', models.BigIntegerField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('EXITOSO', 'Exitoso'), ('FALLIDO', 'Fallido'), ('EN_PROCESO', 'En Proceso')], default='EXITOSO', max_length=20)),
                ('notas', models.TextField(blank=True, null=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respaldos_creados', to='usuarios.usuario')),
            ],
            options={
                'verbose_name': 'Respaldo',
                'verbose_name_plural': 'Respaldos',
                'db_table': 'respaldo',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
