# Generated by Django 5.2.6 on 2025-11-03 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversacionChatbot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('session_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('correo_electronico', models.EmailField(blank=True, max_length=254, null=True)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('ultima_interaccion', models.DateTimeField(auto_now=True)),
                ('contexto', models.JSONField(default=dict, help_text='Estado de la conversación (intent, datos parciales, etc.)')),
                ('paciente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversaciones_chatbot', to='usuarios.paciente')),
            ],
            options={
                'verbose_name': 'Conversación Chatbot',
                'verbose_name_plural': 'Conversaciones Chatbot',
                'db_table': 'conversacion_chatbot',
                'ordering': ['-ultima_interaccion'],
            },
        ),
        migrations.CreateModel(
            name='MensajeChatbot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('tipo', models.CharField(choices=[('usuario', 'Usuario'), ('bot', 'Bot'), ('sistema', 'Sistema')], max_length=10)),
                ('mensaje', models.TextField()),
                ('metadata', models.JSONField(default=dict, help_text='Información adicional (intent detectado, entities, etc.)')),
                ('conversacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='chatbot.conversacionchatbot')),
            ],
            options={
                'verbose_name': 'Mensaje Chatbot',
                'verbose_name_plural': 'Mensajes Chatbot',
                'db_table': 'mensaje_chatbot',
                'ordering': ['fecha_creacion'],
            },
        ),
    ]
