# Generated by Django 5.2.6 on 2025-10-30 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloqueoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField(blank=True, help_text='Fecha de fin del bloqueo', null=True)),
                ('motivo', models.TextField(help_text='Motivo del bloqueo')),
                ('activo', models.BooleanField(default=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bloqueos_creados', to='usuarios.usuario')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloqueos', to='usuarios.usuario')),
            ],
            options={
                'verbose_name': 'Bloqueo de Usuario',
                'verbose_name_plural': 'Bloqueos de Usuarios',
                'db_table': 'bloqueo_usuario',
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
