# Generated by Django 5.2.6 on 2025-11-02 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesionales', '0001_initial'),
        ('tratamientos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SesionTratamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=50, unique=True)),
                ('numero_sesion', models.IntegerField(help_text='Número de sesión dentro del plan')),
                ('titulo', models.CharField(help_text='Título descriptivo de la sesión', max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('programada', 'Programada'), ('en_curso', 'En Curso'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], db_index=True, default='programada', max_length=20)),
                ('fecha_programada', models.DateTimeField()),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('duracion_minutos', models.IntegerField(blank=True, help_text='Duración real de la sesión', null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('recomendaciones', models.TextField(blank=True, help_text='Recomendaciones post-sesión', null=True)),
                ('proxima_sesion_programada', models.DateField(blank=True, null=True)),
                ('odontologo', models.ForeignKey(db_column='odontologocodigo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sesiones_realizadas', to='profesionales.odontologo')),
                ('plan_tratamiento', models.ForeignKey(db_column='idplantratamiento', on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to='tratamientos.plantratamiento')),
            ],
            options={
                'verbose_name': 'Sesión de Tratamiento',
                'verbose_name_plural': 'Sesiones de Tratamiento',
                'db_table': 'sesion_tratamiento',
                'ordering': ['-fecha_programada'],
                'unique_together': {('plan_tratamiento', 'numero_sesion')},
            },
        ),
    ]
