# Generated by Django 5.2.6 on 2025-11-02 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tratamientos', '0002_sesiontratamiento'),
    ]

    operations = [
    ]
