# Generated by Django 5.2.6 on 2025-11-04 03:28

from django.db import migrations


def restaurar_tablas_si_no_existen(apps, schema_editor):
    """
    Restaura las tablas que fueron eliminadas por error en la migración
    historial_clinico.0008
    """
    from django.db import connection
    
    with connection.cursor() as cursor:
        # Verificar si la tabla plan_tratamiento existe
        cursor.execute("""
            SELECT EXISTS (
                SELECT FROM information_schema.tables 
                WHERE table_schema = 'public' 
                AND table_name = 'plan_tratamiento'
            );
        """)
        exists = cursor.fetchone()[0]
        
        if not exists:
            print("⚠️  Recreando tablas eliminadas por migración anterior...")
            
            # Recrear tabla plan_tratamiento
            cursor.execute("""
                CREATE TABLE plan_tratamiento (
                    id bigserial PRIMARY KEY,
                    codigo varchar(50) UNIQUE NOT NULL,
                    descripcion text NOT NULL,
                    diagnostico text,
                    observaciones text,
                    estado varchar(20) NOT NULL DEFAULT 'borrador',
                    fecha_creacion timestamp with time zone NOT NULL DEFAULT NOW(),
                    fecha_aprobacion timestamp with time zone,
                    fecha_inicio date,
                    fecha_finalizacion date,
                    duracion_estimada_dias integer,
                    pacientecodigo bigint NOT NULL REFERENCES paciente(codusuario) ON DELETE CASCADE,
                    odontologocodigo bigint REFERENCES odontologo(codusuario) ON DELETE SET NULL
                );
                
                CREATE INDEX plan_tratamiento_codigo_idx ON plan_tratamiento(codigo);
                CREATE INDEX plan_tratamiento_estado_idx ON plan_tratamiento(estado);
                CREATE INDEX plan_tratamiento_paciente_idx ON plan_tratamiento(pacientecodigo);
                CREATE INDEX plan_tratamiento_odontologo_idx ON plan_tratamiento(odontologocodigo);
            """)
            
            # Recrear tabla presupuesto
            cursor.execute("""
                CREATE TABLE presupuesto (
                    id bigserial PRIMARY KEY,
                    codigo varchar(50) UNIQUE NOT NULL,
                    subtotal numeric(10,2) NOT NULL CHECK (subtotal >= 0),
                    descuento numeric(10,2) NOT NULL DEFAULT 0 CHECK (descuento >= 0),
                    impuesto numeric(10,2) NOT NULL DEFAULT 0 CHECK (impuesto >= 0),
                    total numeric(10,2) NOT NULL CHECK (total >= 0),
                    estado varchar(20) NOT NULL DEFAULT 'pendiente',
                    notas text,
                    fecha_creacion timestamp with time zone NOT NULL DEFAULT NOW(),
                    fecha_vencimiento date,
                    fecha_aprobacion timestamp with time zone,
                    aprobado_por varchar(200),
                    motivo_rechazo text,
                    idplantratamiento bigint NOT NULL REFERENCES plan_tratamiento(id) ON DELETE CASCADE
                );
                
                CREATE INDEX presupuesto_codigo_idx ON presupuesto(codigo);
                CREATE INDEX presupuesto_estado_idx ON presupuesto(estado);
                CREATE INDEX presupuesto_plan_idx ON presupuesto(idplantratamiento);
            """)
            
            # Recrear tabla item_presupuesto
            cursor.execute("""
                CREATE TABLE item_presupuesto (
                    id bigserial PRIMARY KEY,
                    descripcion text,
                    cantidad integer NOT NULL DEFAULT 1 CHECK (cantidad >= 1),
                    precio_unitario numeric(10,2) NOT NULL CHECK (precio_unitario >= 0),
                    descuento_item numeric(10,2) NOT NULL DEFAULT 0 CHECK (descuento_item >= 0),
                    total numeric(10,2) NOT NULL CHECK (total >= 0),
                    numero_diente integer CHECK (numero_diente >= 1),
                    idpresupuesto bigint NOT NULL REFERENCES presupuesto(id) ON DELETE CASCADE,
                    idservicio bigint NOT NULL REFERENCES servicio(id) ON DELETE CASCADE
                );
                
                CREATE INDEX item_presupuesto_presupuesto_idx ON item_presupuesto(idpresupuesto);
                CREATE INDEX item_presupuesto_servicio_idx ON item_presupuesto(idservicio);
            """)
            
            # Recrear tabla procedimiento
            cursor.execute("""
                CREATE TABLE procedimiento (
                    id bigserial PRIMARY KEY,
                    numero_diente integer CHECK (numero_diente >= 1),
                    descripcion text NOT NULL,
                    estado varchar(20) NOT NULL DEFAULT 'pendiente',
                    fecha_planificada date,
                    fecha_realizado timestamp with time zone,
                    duracion_minutos integer,
                    costo_estimado numeric(10,2) CHECK (costo_estimado >= 0),
                    costo_real numeric(10,2) CHECK (costo_real >= 0),
                    notas text,
                    complicaciones text,
                    idplantratamiento bigint NOT NULL REFERENCES plan_tratamiento(id) ON DELETE CASCADE,
                    odontologocodigo bigint REFERENCES odontologo(codusuario) ON DELETE SET NULL,
                    idservicio bigint NOT NULL REFERENCES servicio(id) ON DELETE CASCADE
                );
                
                CREATE INDEX procedimiento_estado_idx ON procedimiento(estado);
                CREATE INDEX procedimiento_plan_idx ON procedimiento(idplantratamiento);
                CREATE INDEX procedimiento_odontologo_idx ON procedimiento(odontologocodigo);
            """)
            
            # Recrear tabla historial_pago
            cursor.execute("""
                CREATE TABLE historial_pago (
                    id bigserial PRIMARY KEY,
                    codigo varchar(50) UNIQUE NOT NULL,
                    monto numeric(10,2) NOT NULL CHECK (monto >= 0.01),
                    metodo_pago varchar(20) NOT NULL,
                    estado varchar(20) NOT NULL DEFAULT 'completado',
                    fecha_pago timestamp with time zone NOT NULL DEFAULT NOW(),
                    numero_comprobante varchar(100),
                    numero_transaccion varchar(100),
                    notas text,
                    registrado_por varchar(200) NOT NULL,
                    idplantratamiento bigint NOT NULL REFERENCES plan_tratamiento(id) ON DELETE CASCADE,
                    idpresupuesto bigint REFERENCES presupuesto(id) ON DELETE SET NULL
                );
                
                CREATE INDEX historial_pago_codigo_idx ON historial_pago(codigo);
                CREATE INDEX historial_pago_estado_idx ON historial_pago(estado);
                CREATE INDEX historial_pago_plan_idx ON historial_pago(idplantratamiento);
            """)
            
            print("✅ Tablas restauradas exitosamente")
        else:
            print("✅ Las tablas ya existen, no se requiere restauración")


class Migration(migrations.Migration):

    dependencies = [
        ('tratamientos', '0003_agregar_sesion_tratamiento'),
        ('historial_clinico', '0008_remove_plantratamiento_odontologo_and_more'),
    ]

    operations = [
        migrations.RunPython(restaurar_tablas_si_no_existen, migrations.RunPython.noop),
    ]
