# Generated by Django 5.2.6 on 2025-10-30 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historialclinico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('pacientecodigo', models.ForeignKey(db_column='pacientecodigo', on_delete=django.db.models.deletion.CASCADE, related_name='historiales', to='usuarios.paciente')),
            ],
            options={
                'verbose_name': 'Historial Clinico',
                'verbose_name_plural': 'Historiales Clinicos',
                'db_table': 'historialclinico',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoClinico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('archivo_url', models.CharField(max_length=512)),
                ('tipo_documento', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('historial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='historial_clinico.historialclinico')),
            ],
            options={
                'verbose_name': 'Documento Clinico',
                'verbose_name_plural': 'Documentos Clinicos',
                'db_table': 'documento_clinico',
                'ordering': ['-fecha_subida'],
            },
        ),
    ]
