# Generated by Django 5.2.6 on 2025-10-30 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historial_clinico', '0001_initial'),
        ('profesionales', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Odontograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('dientes', models.JSONField(default=dict, help_text='Estructura JSON con información de los 32 dientes')),
                ('observaciones_generales', models.TextField(blank=True)),
                ('odontologo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='odontogramas_realizados', to='profesionales.odontologo')),
                ('paciente', models.ForeignKey(db_column='pacientecodigo', on_delete=django.db.models.deletion.CASCADE, related_name='odontogramas', to='usuarios.paciente')),
            ],
            options={
                'verbose_name': 'Odontograma',
                'verbose_name_plural': 'Odontogramas',
                'db_table': 'odontograma',
                'ordering': ['-fecha_actualizacion'],
            },
        ),
        migrations.CreateModel(
            name='TratamientoOdontologico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_diente', models.IntegerField(help_text='Número del diente tratado (1-32)')),
                ('tipo_tratamiento', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('fecha_tratamiento', models.DateField()),
                ('costo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('odontograma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tratamientos', to='historial_clinico.odontograma')),
            ],
            options={
                'verbose_name': 'Tratamiento Odontológico',
                'verbose_name_plural': 'Tratamientos Odontológicos',
                'db_table': 'tratamiento_odontologico',
                'ordering': ['-fecha_tratamiento'],
            },
        ),
    ]
