# Generated by Django 5.2.6 on 2025-10-30 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historial_clinico', '0002_odontograma_tratamientoodontologico'),
        ('profesionales', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentimientoInformado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_tratamiento', models.CharField(max_length=200)),
                ('contenido_documento', models.TextField(help_text='Texto completo del consentimiento informado')),
                ('riesgos', models.TextField(blank=True, help_text='Riesgos asociados al tratamiento', null=True)),
                ('beneficios', models.TextField(blank=True, help_text='Beneficios esperados del tratamiento', null=True)),
                ('alternativas', models.TextField(blank=True, help_text='Tratamientos alternativos disponibles', null=True)),
                ('firma_paciente_url', models.CharField(blank=True, help_text='URL de la imagen de la firma del paciente', max_length=512, null=True)),
                ('firma_tutor_url', models.CharField(blank=True, help_text='URL de la firma del tutor legal (para menores)', max_length=512, null=True)),
                ('nombre_tutor', models.CharField(blank=True, help_text='Nombre completo del tutor legal', max_length=200, null=True)),
                ('documento_tutor', models.CharField(blank=True, help_text='Documento de identidad del tutor', max_length=50, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de Firma'), ('firmado', 'Firmado'), ('rechazado', 'Rechazado'), ('vencido', 'Vencido')], db_index=True, default='pendiente', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_firma', models.DateTimeField(blank=True, null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, help_text='Fecha hasta la cual es válido el consentimiento', null=True)),
                ('ip_firma', models.GenericIPAddressField(blank=True, help_text='Dirección IP desde donde se firmó', null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('odontologo', models.ForeignKey(db_column='odontologocodigo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consentimientos_creados', to='profesionales.odontologo')),
                ('paciente', models.ForeignKey(db_column='pacientecodigo', on_delete=django.db.models.deletion.CASCADE, related_name='consentimientos', to='usuarios.paciente')),
            ],
            options={
                'verbose_name': 'Consentimiento Informado',
                'verbose_name_plural': 'Consentimientos Informados',
                'db_table': 'consentimiento_informado',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
