# Generated by Django 5.2.6 on 2025-10-31 00:06

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion_clinica', '0001_initial'),
        ('historial_clinico', '0004_categoriainsumo_proveedor_insumo_alertainventario_and_more'),
        ('profesionales', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanTratamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=50, unique=True)),
                ('descripcion', models.TextField()),
                ('diagnostico', models.TextField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('aprobado', 'Aprobado'), ('en_proceso', 'En Proceso'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], db_index=True, default='borrador', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_finalizacion', models.DateField(blank=True, null=True)),
                ('duracion_estimada_dias', models.IntegerField(blank=True, help_text='Duración estimada en días', null=True)),
                ('odontologo', models.ForeignKey(db_column='odontologocodigo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planes_creados', to='profesionales.odontologo')),
                ('paciente', models.ForeignKey(db_column='pacientecodigo', on_delete=django.db.models.deletion.CASCADE, related_name='planes_tratamiento', to='usuarios.paciente')),
            ],
            options={
                'verbose_name': 'Plan de Tratamiento',
                'verbose_name_plural': 'Planes de Tratamiento',
                'db_table': 'plan_tratamiento',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=50, unique=True)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('descuento', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('impuesto', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('vencido', 'Vencido')], db_index=True, default='pendiente', max_length=20)),
                ('notas', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
                ('aprobado_por', models.CharField(blank=True, max_length=200, null=True)),
                ('motivo_rechazo', models.TextField(blank=True, null=True)),
                ('plan_tratamiento', models.ForeignKey(db_column='idplantratamiento', on_delete=django.db.models.deletion.CASCADE, related_name='presupuestos', to='historial_clinico.plantratamiento')),
            ],
            options={
                'verbose_name': 'Presupuesto',
                'verbose_name_plural': 'Presupuestos',
                'db_table': 'presupuesto',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ItemPresupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción adicional del servicio', null=True)),
                ('cantidad', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('descuento_item', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('numero_diente', models.IntegerField(blank=True, help_text='Número de diente si aplica (1-32)', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('servicio', models.ForeignKey(db_column='idservicio', on_delete=django.db.models.deletion.CASCADE, to='administracion_clinica.servicio')),
                ('presupuesto', models.ForeignKey(db_column='idpresupuesto', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='historial_clinico.presupuesto')),
            ],
            options={
                'verbose_name': 'Item de Presupuesto',
                'verbose_name_plural': 'Items de Presupuesto',
                'db_table': 'item_presupuesto',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Procedimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_diente', models.IntegerField(blank=True, help_text='Número de diente tratado (1-32)', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], db_index=True, default='pendiente', max_length=20)),
                ('fecha_planificada', models.DateField(blank=True, null=True)),
                ('fecha_realizado', models.DateTimeField(blank=True, null=True)),
                ('duracion_minutos', models.IntegerField(blank=True, null=True)),
                ('costo_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('costo_real', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('notas', models.TextField(blank=True, null=True)),
                ('complicaciones', models.TextField(blank=True, null=True)),
                ('odontologo', models.ForeignKey(db_column='odontologocodigo', null=True, on_delete=django.db.models.deletion.SET_NULL, to='profesionales.odontologo')),
                ('plan_tratamiento', models.ForeignKey(db_column='idplantratamiento', on_delete=django.db.models.deletion.CASCADE, related_name='procedimientos', to='historial_clinico.plantratamiento')),
                ('servicio', models.ForeignKey(db_column='idservicio', on_delete=django.db.models.deletion.CASCADE, to='administracion_clinica.servicio')),
            ],
            options={
                'verbose_name': 'Procedimiento',
                'verbose_name_plural': 'Procedimientos',
                'db_table': 'procedimiento',
                'ordering': ['fecha_planificada', 'id'],
            },
        ),
    ]
