# Generated by Django 5.2.6 on 2025-10-31 23:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historial_clinico', '0005_plantratamiento_presupuesto_itempresupuesto_and_more'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historialclinico',
            options={'ordering': ['-fecha', '-episodio'], 'verbose_name': 'Historia Clínica', 'verbose_name_plural': 'Historias Clínicas'},
        ),
        migrations.AddField(
            model_name='historialclinico',
            name='alergias',
            field=models.TextField(blank=True, help_text='Alergias conocidas del paciente', null=True, verbose_name='Alergias'),
        ),
        migrations.AddField(
            model_name='historialclinico',
            name='antecedentesfamiliares',
            field=models.TextField(blank=True, help_text='Historial médico familiar relevante', null=True, verbose_name='Antecedentes Familiares'),
        ),
        migrations.AddField(
            model_name='historialclinico',
            name='antecedentespersonales',
            field=models.TextField(blank=True, help_text='Historial médico personal', null=True, verbose_name='Antecedentes Personales'),
        ),
        migrations.AddField(
            model_name='historialclinico',
            name='diagnostico',
            field=models.TextField(blank=True, help_text='Diagnóstico médico/odontológico', null=True, verbose_name='Diagnóstico'),
        ),
        migrations.AddField(
            model_name='historialclinico',
            name='enfermedades',
            field=models.TextField(blank=True, help_text='Enfermedades previas o crónicas', null=True, verbose_name='Enfermedades'),
        ),
        migrations.AddField(
            model_name='historialclinico',
            name='episodio',
            field=models.IntegerField(default=1, help_text='Número secuencial de consulta para este paciente', verbose_name='Número de Episodio'),
        ),
        migrations.AddField(
            model_name='historialclinico',
            name='examenbucal',
            field=models.TextField(blank=True, help_text='Examen odontológico específico', null=True, verbose_name='Examen Bucal'),
        ),
        migrations.AddField(
            model_name='historialclinico',
            name='examengeneral',
            field=models.TextField(blank=True, help_text='Resultados del examen físico general', null=True, verbose_name='Examen General'),
        ),
        migrations.AddField(
            model_name='historialclinico',
            name='examenregional',
            field=models.TextField(blank=True, help_text='Examen regional o segmentario', null=True, verbose_name='Examen Regional'),
        ),
        migrations.AddField(
            model_name='historialclinico',
            name='motivoconsulta',
            field=models.TextField(blank=True, help_text='Razón por la que el paciente consulta', null=True, verbose_name='Motivo de Consulta'),
        ),
        migrations.AddField(
            model_name='historialclinico',
            name='receta',
            field=models.TextField(blank=True, help_text='Prescripción de medicamentos', null=True, verbose_name='Receta Médica'),
        ),
        migrations.AddField(
            model_name='historialclinico',
            name='tratamiento',
            field=models.TextField(blank=True, help_text='Tratamiento prescrito o realizado', null=True, verbose_name='Tratamiento'),
        ),
        migrations.AddField(
            model_name='historialclinico',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Última Actualización'),
        ),
        migrations.AlterField(
            model_name='historialclinico',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Campo general (legacy)', null=True, verbose_name='Descripción General'),
        ),
        migrations.AlterField(
            model_name='historialclinico',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='historialclinico',
            name='pacientecodigo',
            field=models.ForeignKey(db_column='pacientecodigo', on_delete=django.db.models.deletion.CASCADE, related_name='historiales', to='usuarios.paciente', verbose_name='Paciente'),
        ),
        migrations.AlterUniqueTogether(
            name='historialclinico',
            unique_together={('pacientecodigo', 'episodio')},
        ),
        migrations.AddIndex(
            model_name='historialclinico',
            index=models.Index(fields=['pacientecodigo', '-fecha'], name='historialcl_pacient_1a0927_idx'),
        ),
        migrations.AddIndex(
            model_name='historialclinico',
            index=models.Index(fields=['pacientecodigo', 'episodio'], name='historialcl_pacient_c55974_idx'),
        ),
    ]
