# Generated by Django 5.2.6 on 2025-11-01 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historial_clinico', '0006_alter_historialclinico_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialclinico',
            name='episodio',
            field=models.IntegerField(blank=True, help_text='Número secuencial de consulta para este paciente (auto-generado)', null=True, verbose_name='Número de Episodio'),
        ),
    ]
