# Generated by Django 5.2.6 on 2025-11-04 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historial_clinico', '0007_episodio_nullable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantratamiento',
            name='odontologo',
        ),
        migrations.RemoveField(
            model_name='plantratamiento',
            name='paciente',
        ),
        migrations.RemoveField(
            model_name='procedimiento',
            name='plan_tratamiento',
        ),
        migrations.RemoveField(
            model_name='presupuesto',
            name='plan_tratamiento',
        ),
        migrations.RemoveField(
            model_name='procedimiento',
            name='odontologo',
        ),
        migrations.RemoveField(
            model_name='procedimiento',
            name='servicio',
        ),
        migrations.AlterField(
            model_name='consentimientoinformado',
            name='firma_paciente_url',
            field=models.TextField(blank=True, help_text='URL o base64 data URI de la imagen de la firma del paciente', null=True),
        ),
        migrations.AlterField(
            model_name='consentimientoinformado',
            name='firma_tutor_url',
            field=models.TextField(blank=True, help_text='URL o base64 data URI de la firma del tutor legal (para menores)', null=True),
        ),
        migrations.DeleteModel(
            name='ItemPresupuesto',
        ),
        migrations.DeleteModel(
            name='PlanTratamiento',
        ),
        migrations.DeleteModel(
            name='Presupuesto',
        ),
        migrations.DeleteModel(
            name='Procedimiento',
        ),
    ]
