# Generated by Django 5.2.6 on 2025-11-04 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0001_initial'),
        ('historial_clinico', '0008_remove_plantratamiento_odontologo_and_more'),
        ('profesionales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consentimientoinformado',
            name='consulta',
            field=models.ForeignKey(blank=True, help_text='Cita/consulta asociada al consentimiento', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consentimientos', to='citas.consulta'),
        ),
        migrations.AlterField(
            model_name='consentimientoinformado',
            name='odontologo',
            field=models.ForeignKey(blank=True, db_column='odontologocodigo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consentimientos_creados', to='profesionales.odontologo'),
        ),
    ]
