# Generated by Django 5.2.6 on 2025-10-30 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('costobase', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duracion', models.IntegerField(default=30, help_text='Duracion estimada en minutos')),
                ('activo', models.BooleanField(default=True, help_text='Servicio disponible')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'db_table': 'servicio',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ComboServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tipo_precio', models.CharField(choices=[('PORCENTAJE', 'Descuento Porcentual'), ('MONTO_FIJO', 'Monto Fijo'), ('PROMOCION', 'Precio Promocional')], default='PORCENTAJE', max_length=20)),
                ('valor_precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Combo de Servicios',
                'verbose_name_plural': 'Combos de Servicios',
                'db_table': 'combo_servicio',
                'ordering': ['-fecha_creacion'],
                'constraints': [models.CheckConstraint(condition=models.Q(('valor_precio__gte', 0)), name='combo_valor_precio_no_negativo')],
            },
        ),
        migrations.CreateModel(
            name='ComboServicioDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('combo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='administracion_clinica.comboservicio')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='combos_detalle', to='administracion_clinica.servicio')),
            ],
            options={
                'verbose_name': 'Detalle de Combo',
                'verbose_name_plural': 'Detalles de Combos',
                'db_table': 'combo_servicio_detalle',
                'ordering': ['orden', 'id'],
                'constraints': [models.UniqueConstraint(fields=('combo', 'servicio'), name='unique_combo_servicio'), models.CheckConstraint(condition=models.Q(('cantidad__gt', 0)), name='combo_detalle_cantidad_positiva')],
            },
        ),
    ]
