# Generated by Django 5.2.6 on 2025-10-30 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('correoelectronico', models.CharField(max_length=255, unique=True)),
                ('sexo', models.CharField(blank=True, max_length=50, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('recibir_notificaciones', models.BooleanField(default=True)),
                ('notificaciones_email', models.BooleanField(default=True)),
                ('notificaciones_push', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='Tipodeusuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Tipo de Usuario',
                'verbose_name_plural': 'Tipos de Usuario',
                'db_table': 'tipodeusuario',
                'ordering': ['rol'],
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('codusuario', models.OneToOneField(db_column='codusuario', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='usuarios.usuario')),
                ('carnetidentidad', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('fechanacimiento', models.DateField(blank=True, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'db_table': 'paciente',
            },
        ),
        migrations.AddField(
            model_name='usuario',
            name='idtipousuario',
            field=models.ForeignKey(db_column='idtipousuario', on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.tipodeusuario'),
        ),
    ]
