# Generated by Django for Multitenancy

from django.db import migrations, models
import django.db.models.deletion
import django_tenants.postgresql_backend.base


class Migration(migrations.Migration):

    dependencies = [
        ('comun', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.CharField(db_index=True, max_length=63, unique=True, validators=[django_tenants.postgresql_backend.base._check_schema_name])),
                ('nombre', models.CharField(help_text='Nombre de la clínica', max_length=200)),
                ('ruc', models.CharField(help_text='RUC/NIT de la clínica', max_length=20, unique=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('admin_nombre', models.CharField(help_text='Nombre del administrador', max_length=200)),
                ('admin_email', models.EmailField(help_text='Email del administrador', max_length=254)),
                ('admin_telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('activa', models.BooleanField(default=True, help_text='Si la clínica está activa')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('plan', models.CharField(choices=[('basico', 'Básico'), ('profesional', 'Profesional'), ('empresarial', 'Empresarial')], default='basico', max_length=20)),
                ('max_usuarios', models.IntegerField(default=10, help_text='Máximo de usuarios permitidos')),
                ('max_pacientes', models.IntegerField(default=100, help_text='Máximo de pacientes permitidos')),
                ('logo_url', models.URLField(blank=True, help_text='URL del logo en S3', null=True)),
            ],
            options={
                'verbose_name': 'Clínica',
                'verbose_name_plural': 'Clínicas',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Dominio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=253, unique=True)),
                ('is_primary', models.BooleanField(db_index=True, default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='comun.clinica')),
            ],
            options={
                'verbose_name': 'Dominio',
                'verbose_name_plural': 'Dominios',
                'abstract': False,
            },
        ),
    ]
