# Generated by Django 5.2.6 on 2025-11-03 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Respaldo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('completo', 'Respaldo Completo'), ('incremental', 'Respaldo Incremental'), ('manual', 'Respaldo Manual')], default='completo', max_length=20)),
                ('estado', models.CharField(choices=[('en_proceso', 'En Proceso'), ('completado', 'Completado'), ('fallido', 'Fallido')], default='en_proceso', max_length=20)),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('ruta_nube', models.CharField(help_text='Ruta en S3', max_length=500)),
                ('tamano_bytes', models.BigIntegerField(default=0)),
                ('hash_md5', models.CharField(help_text='Hash MD5 para verificar integridad', max_length=32)),
                ('tablas_respaldadas', models.JSONField(default=list, help_text='Lista de tablas incluidas')),
                ('registros_totales', models.IntegerField(default=0)),
                ('tiempo_ejecucion', models.DurationField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_expiracion', models.DateTimeField(blank=True, help_text='Fecha en que se eliminará automáticamente', null=True)),
                ('notas', models.TextField(blank=True)),
                ('error_mensaje', models.TextField(blank=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respaldos_creados', to='usuarios.usuario')),
            ],
            options={
                'db_table': 'respaldo',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['-fecha_creacion'], name='respaldo_fecha_c_2f55c5_idx'), models.Index(fields=['estado', 'fecha_creacion'], name='respaldo_estado_a480f3_idx')],
            },
        ),
    ]
