# Generated by Django 5.2.6 on 2025-10-30 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('citas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estadodefactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Estado de Factura',
                'verbose_name_plural': 'Estados de Factura',
                'db_table': 'estadodefactura',
                'ordering': ['estado'],
            },
        ),
        migrations.CreateModel(
            name='Tipopago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrepago', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo de Pago',
                'verbose_name_plural': 'Tipos de Pago',
                'db_table': 'tipopago',
                'ordering': ['nombrepago'],
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaemision', models.DateField()),
                ('montototal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('idestadofactura', models.ForeignKey(db_column='idestadofactura', on_delete=django.db.models.deletion.DO_NOTHING, to='sistema_pagos.estadodefactura')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'db_table': 'factura',
                'ordering': ['-fechaemision'],
            },
        ),
        migrations.CreateModel(
            name='Itemdefactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('idfactura', models.ForeignKey(db_column='idfactura', on_delete=django.db.models.deletion.DO_NOTHING, to='sistema_pagos.factura')),
            ],
            options={
                'verbose_name': 'Item de Factura',
                'verbose_name_plural': 'Items de Factura',
                'db_table': 'itemdefactura',
            },
        ),
        migrations.CreateModel(
            name='PagoEnLinea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_pago', models.CharField(max_length=50, unique=True)),
                ('origen_tipo', models.CharField(choices=[('plan_completo', 'Plan de Tratamiento Completo'), ('items_individuales', 'Items Individuales del Plan'), ('consulta', 'Consulta/Cita')], max_length=30)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('moneda', models.CharField(default='BOB', max_length=3)),
                ('monto_original', models.DecimalField(decimal_places=2, max_digits=10)),
                ('saldo_anterior', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('saldo_nuevo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('procesando', 'Procesando'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('cancelado', 'Cancelado'), ('reembolsado', 'Reembolsado'), ('anulado', 'Anulado')], default='pendiente', max_length=20)),
                ('metodo_pago', models.CharField(choices=[('tarjeta', 'Tarjeta de Credito/Debito'), ('transferencia', 'Transferencia Bancaria'), ('qr', 'Codigo QR')], default='tarjeta', max_length=20)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('stripe_charge_id', models.CharField(blank=True, max_length=255, null=True)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=255, null=True)),
                ('stripe_metadata', models.JSONField(blank=True, default=dict)),
                ('descripcion', models.TextField()),
                ('motivo_rechazo', models.TextField(blank=True, null=True)),
                ('numero_intentos', models.IntegerField(default=0)),
                ('ultimo_intento', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('consulta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='citas.consulta')),
            ],
            options={
                'verbose_name': 'Pago en Linea',
                'verbose_name_plural': 'Pagos en Linea',
                'db_table': 'pago_en_linea',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montopagado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fechapago', models.DateField()),
                ('idfactura', models.ForeignKey(db_column='idfactura', on_delete=django.db.models.deletion.DO_NOTHING, to='sistema_pagos.factura')),
                ('idtipopago', models.ForeignKey(db_column='idtipopago', on_delete=django.db.models.deletion.DO_NOTHING, to='sistema_pagos.tipopago')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'db_table': 'pago',
                'ordering': ['-fechapago'],
            },
        ),
    ]
